### ISSUE TITLE
How to handling error from Hook function when I use Aync/Await in Hook function

### ISSUE THREAD

**Issue by lagmanzaza** [feathersjs/errors#106]

**Comment by daffl** [comment]
I'm not sure what exactly you are asking but if you `throw` an error in an `async` hook function it will stop and return that error. If you need to handle it you can do that with an `error` hook or - if you want to continue to run other hooks - by wrapping your statement in a normal `try/catch`.

**Comment by lagmanzaza** [comment]
I want stop hook function when a hook function error

**Comment by daffl** [comment]
As [mentioned in the Hook API documentation](https://docs.feathersjs.com/api/hooks.html#throwing-an-error) it will do exactly that if you `throw` an error or return a rejected promise.

**Comment by lagmanzaza** [comment]
Thank you sir

**Comment by shadowRR** [comment]
@daffl Sorry for re-opening this, but i'm having a similar issue. I'm basically throwing an error in an async hook (validations error -> Unprocessable). While my hooks are stopped, and the client is getting the error properly, i'm also getting a `Unhandled rejection` on my server console ? I know i should have a handler on the global level (it's temporarily disabled while testing other stuff), but shouldn't feathers-errors have handled the error to avoid those, since they are actually handled ?
